window.DENGZHOU_LINKS = {
  openAt: "2026-07-09T00:00:00+08:00",
  collection: "https://h5.touchieai.com/combo?code=9867d8f2-939e-480d-8796-276879c7e36f",
  characters: {
    "01": "character-01.html",
    "02": "character-02.html",
    "03": "character-03.html",
    "04": "character-04.html",
    "05": "character-05.html",
  },
  dailyLanterns: [
    {
      date: "2026-07-03",
      title: "第一盞燈",
      name: "初燈乍明",
      image: "assets/day1.webp",
      downloadName: "沐眠-第一盞燈-初燈乍明.webp",
    },
    {
      date: "2026-07-04",
      title: "第二盞燈",
      name: "萬燈騰空",
      image: "assets/day2.webp",
      downloadName: "沐眠-第二盞燈-萬燈騰空.webp",
    },
    {
      date: "2026-07-05",
      title: "第三盞燈",
      name: "燈晝長明",
      image: "assets/day3.webp",
      downloadName: "沐眠-第三盞燈-燈晝長明.webp",
    },
    {
      date: "2026-07-06",
      title: "第四盞燈",
      name: "流光未歇",
      image: "assets/day4.webp",
      downloadName: "沐眠-第四盞燈-流光未歇.webp",
    },
    {
      date: "2026-07-07",
      title: "第五盞燈",
      name: "餘燼微溫",
      image: "assets/day5.webp",
      downloadName: "沐眠-第五盞燈-餘燼微溫.webp",
    },
    {
      date: "2026-07-08",
      title: "第六盞燈",
      name: "餘燼殘影",
      image: "assets/day6.webp",
      downloadName: "沐眠-第六盞燈-餘燼殘影.webp",
    },
    {
      date: "2026-07-08",
      title: "第七盞燈",
      name: "燈晝終章",
      image: "assets/day7.webp",
      downloadName: "沐眠-第七盞燈-燈晝終章.webp",
    },
  ],
};
